name: Sync from UMKK and ULLL into RU-NWC

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RU-NWC
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setting remotes
        run: |
          git remote add repo-ulll https://github.com/ulll-nav/ulll-sector-package.git || true
          git remote add repo-umkk https://github.com/ulll-nav/umkk-sector-package.git || true
          git fetch repo-ulll
          git fetch repo-umkk

      - name: Merge from ULLL
        run: |
          git merge repo-ulll/master --allow-unrelated-histories -m "chore: merge from ULLL @${{ github.run_id }}"
      
      - name: Merge from UMKK
        run: |
          git merge repo-umkk/master --allow-unrelated-histories -m "chore: merge from UMKK @${{ github.run_id }}"

      - name: Unify UMKK into ULLL
        run: |
          if [ -d UMKK ]; then
            git mv UMKK/* ULLL/
            git rm -rf UMKK
            git commit -m "chore: unify UMKK into ULLL"
          else
            echo "No UMKK directory to unify"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
