name: Overwrite from ULLL/UMKK on dispatch

on:
  repository_dispatch:
    types: [sync-update]

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT_TOKEN }}
      ORG: ulll-nav

    steps:
      - name: Checkout northwest-sector-package
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ env.PAT }}

      - name: Configure fallback Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set dispatch variables
        run: |
          echo "SOURCE=${{ github.event.client_payload.source }}" >> $GITHUB_ENV
          echo "SHA=${{ github.event.client_payload.sha }}"   >> $GITHUB_ENV

      - name: Fetch ULLL into temp
        if: env.SOURCE == 'ULLL'
        run: |
          git remote add ul https://x-access-token:${{ env.PAT }}@github.com/${{ env.ORG }}/ulll-sector-package.git || true
          REF="${SHA:-main}"
          git fetch ul "$REF"
          mkdir -p /tmp/ulll
          git --work-tree=/tmp/ulll checkout ul/"$REF" -- . ':(exclude).github'

      - name: Capture ULLL author/msg
        if: env.SOURCE == 'ULLL'
        run: |
          REF="${SHA:-main}"
          read AN AE MSG <<<$(git log ul/"$REF" -1 --pretty="%an %ae %s")
          echo "AUTHOR_NAME=$AN"   >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=$AE"  >> $GITHUB_ENV
          echo "COMMIT_MSG=$MSG"    >> $GITHUB_ENV

      - name: Sync ULLL content
        if: env.SOURCE == 'ULLL'
        run: |
          mkdir -p ULLL
          rsync -a --delete --exclude='.git' --exclude='.github' /tmp/ulll/ULLL/ ULLL/
          rsync -a --exclude='.git' --exclude='.github' /tmp/ulll/*.prf ./
          rm -rf /tmp/ulll
          git add -A

      - name: Commit ULLL sync
        if: env.SOURCE == 'ULLL'
        run: |
          git config user.name  "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          if ! git diff --cached --quiet; then
            git commit \
              --author="$AUTHOR_NAME <$AUTHOR_EMAIL>" \
              -m "commit from ULLL: $COMMIT_MSG
            Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          fi

      - name: Fetch UMKK into temp
        if: env.SOURCE == 'UMKK'
        run: |
          git remote add um https://x-access-token:${{ env.PAT }}@github.com/${{ env.ORG }}/umkk-sector-package.git || true
          REF="${SHA:-main}"
          git fetch um "$REF"
          mkdir -p /tmp/umkk
          git --work-tree=/tmp/umkk checkout um/"$REF" -- . ':(exclude).github'

      - name: Capture UMKK author/msg
        if: env.SOURCE == 'UMKK'
        run: |
          REF="${SHA:-main}"
          read AN AE MSG <<<$(git log um/"$REF" -1 --pretty="%an %ae %s")
          echo "AUTHOR_NAME=$AN"   >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=$AE"  >> $GITHUB_ENV
          echo "COMMIT_MSG=$MSG"    >> $GITHUB_ENV

      - name: Sync UMKK content
        if: env.SOURCE == 'UMKK'
        run: |
          mkdir -p ULLL
          rsync -a --delete --exclude='.git' --exclude='.github' /tmp/umkk/UMKK/ ULLL/
          rsync -a --exclude='.git' --exclude='.github' /tmp/umkk/*.prf ./
          rsync -a /tmp/umkk/UMKK/Settings/Kaliningrad ULLL/Settings/Kaliningrad
          rsync -a /tmp/umkk/UMKK/Plugins/ ULLL/Plugins/
          rm -rf /tmp/umkk
          git add -A

      - name: Replace \UMKK → \ULLL in .prf
        if: env.SOURCE == 'UMKK'
        run: |
          find . -type f -name '*.prf' -print0 | xargs -0 sed -i 's|\\UMKK|\\ULLL|g'
          git add -A

      - name: Commit UMKK sync
        if: env.SOURCE == 'UMKK'
        run: |
          git config user.name  "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          if ! git diff --cached --quiet; then
            git commit \
              --author="$AUTHOR_NAME <$AUTHOR_EMAIL>" \
              -m "commit from UMKK: $COMMIT_MSG
            Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          fi

      - name: Force push
        run: |
          git remote set-url origin https://x-access-token:${{ env.PAT }}@github.com/${{ github.repository }}.git
          git push origin main --force
